app/models.py
#from flask_sqlalchemy import SQLAlchemy
from app import db
#db=SQLAlchemy()

class Contact(db.Model):
    __tablename__='contacts'
    
    id=db.Column(db.Integer(),primary_key=True,autoincrement=True)
    name=db.Column(db.String(55),index=True)
    firstname=db.Column(db.String(20))
    email=db.Column(db.String())
    street=db.Column(db.String(25))
    zip_code=db.Column(db.Integer())
    cityid=db.Column(db.Integer,db.ForeignKey('cities.id'))
    city=db.relationship('City', backref='contacts')
    
    def __repr__(self):
        return '<contact % r>' %self.name

class City(db.Model):
     __tablename__='cities'
     id=db.Column(db.Integer(),primary_key=True,autoincrement=True)
     cityname=db.Column(db.String(40),unique=True)
     
     def __repr__(self):
         return '<city % r>' %self.cityname #.name        	    

app/__init__.py
import sys
from flask import Flask,render_template
from flask_sqlalchemy import SQLAlchemy
from flask_foundation import Foundation
from config import config

db=SQLAlchemy()
foundation=Foundation()

def create_app(config_name):
   app=Flask(__name__)
   app.config.from_object(config[config_name])
   config[config_name].init_app(app)
   
   db.init_app(app)
   foundation.init_app(app)
    
   from main import main as main_blueprint
   app.register_blueprint(main_blueprint)   
   
   return app

app/main/__init__.py
from flask import Blueprint
main=Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, flash, request, session, redirect, url_for
from . import main
from .. import db
from datetime import datetime
from flask_paginate import Pagination,get_page_parameter,get_page_args
from ..models import Contact, City
from .forms import ContactForm



@main.context_processor
def inject_now():
	return {'now':datetime.utcnow()}

@main.route('/',methods=['GET'])
def index():
	return redirect(url_for('main.contacts',page=1))

    	
@main.route('/contacts/')
def contacts(page=1):
	joincondition=(Contact.cityid==City.id)
	
	contacts=db.session.query(Contact).join(City,(joincondition)).order_by(Contact.id.desc())
	
	total=contacts.count()
	
	per_page=2
	
	page=int(request.args.get("page",1))
	
	factor=page-1
	
	ofset=factor*per_page
	
	shown_contacts=contacts.limit(per_page).offset(ofset)
	
	paging=Pagination(page=page,per_page=per_page,offset=ofset,total=total,record_name=contacts,css_framework='foundation')
	
	return render_template('contacts.html',contacts=shown_contacts,page=page,offset=ofset,pagination=paging)
	
	    	
@main.route('/contacts/edit/<int:id>',methods=['GET','POST'])
def editContact(id):
    form=ContactForm(csrf_enabled=False)
       
    my_contact = db.session.query(Contact).get(id)
    
    city_id=my_contact.cityid
    cities=[(c.id,c.cityname) for c in db.session.query(City).all()]
    mycity_name = db.session.query(City).get(city_id)
    my_city=(city_id,mycity_name) 
    
    if request.method == 'GET' and my_contact is not None:
    	  cities=[(c.id,c.cityname) for c in db.session.query(City).all()]
    	  form.name.data = my_contact.name
    	  form.firstname.data = my_contact.firstname
    	  form.email.data = my_contact.email
    	  form.street.data = my_contact.street
    	  form.zip_code.data = my_contact.zip_code
    	  form.city.choices=cities
    	  form.city.default=my_city
    	  form.city.data = my_city[0]
    	     	  
    elif request.method=='GET' and my_contact is None:
    	print("no saved contact")
    	form.city.choices=cities
    
    	   
    	
    form.city.choices=cities
    
    if form.validate_on_submit():
           
        name=form.name.data        
        firstname=form.firstname.data
        email=form.email.data
        street=form.street.data
        zip_code=form.zip_code.data
        city=form.city.data
        
        db.session.query(Contact).filter_by(id=id).update({'name':name,
        'firstname':firstname,
        'street':street,
        'zip_code':zip_code,
        'cityid':city}
        )
        
        db.session.commit()
    
        flash('The contact details %s have been updated' %name,'success')  
        
    return render_template('contact_edit.html',form=form)

    
            	    	
@main.route('/contacts/create',methods=['GET','POST'])
def createContact():
	form=ContactForm(csrf_enabled=False)
	cities=[(c.id,c.cityname) for c in db.session.query(City).all()]
	quest=(0,"Select City")
	form.city.choices=cities
	form.city.default=quest
	
	if form.validate_on_submit():
		name=form.name.data
		firstname=form.firstname.data
		email=form.email.data
		street=form.street.data
		zip_code=form.zip_code.data
		city=form.city.data
		contact=Contact(name=name,firstname=firstname,email=email,street=street,zip_code=zip_code,cityid=city)
		db.session.add(contact)
		db.session.commit()
		
		flash('The new contact %s has been saved' %name,'success')
		
	return render_template('contact_create.html',form=form)

app/templates/base.html
{% extends "foundation_base.html" %}
{%block head%}
{% block title %}{% endblock %}
{{super()}}

{%endblock%}
{%block body%}
                {%block header%}
                {% include 'header.html' %}
                {%endblock%}
                {%block nav%}
                {% include 'menu.html' %}
                {%endblock%}
                {%block flashes%}
                    {% for message in get_flashed_messages()%}
                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{message}}
                    </div>
                    {% endfor %}
                {%endblock%}
                {%block container%}
                  ‘Welcome to web Development with Flask!
                  Oh Yes!’
                {%endblock%}
                {%block footer%}
                {% include 'footer.html' %}
                {%endblock%}
{%endblock%}

app/templates/contacts.html
{% extends "base.html" %}
{% block container%}
<table>
    <thead>
        <th>Full Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Street</th>
        <th>Zip Code</th>
        <th>City</th>
        <th>Action</th>    
    </thead>

        {%for contact in contacts%}
         
    <tr>
        <td>{{contact.name}}</td>
        <td>{{contact.firstname}}</td>
        <td>{{contact.email}}</td>
        <td>{{contact.street}}</td>
        <td>{{contact.zip_code}}</td>
        <td>{{contact.city.cityname}}</td>
        <td><a href="{{url_for('main.editContact',id=contact.id)}}">EDIT</a></td>
    </tr>
       
       {% endfor %}
</table>
{{pagination.links|safe}} 
{% endblock %}

app/templates/footer.html
<h5 id="footer" style="position: fixed;bottom: 0;width:100%;margin-bottom:0;height: 2.5rem;background-color: blue;color: white;"
 >&copy{{now.year}} Benedict Masimbani Productions</h5>

app/templates/header.html
<h1>Address Book</h1>

app/templates/menu.html
<nav>
    <ul>
    
        <li style="display:inline-block;"><a style="text-decoration:none;" href="{{url_for('main.createContact')}}"><button class="button success"> Add Contact</button></a></li>
        <li style="display:inline-block;"><a style="text-decoration:none;" href="{{url_for('main.contacts',page=1)}}"><button class="button success">List Contacts</button></a></li>    
    </ul>    
</nav>